name: tp4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Requperer le code
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependnces
        run: pip install -r requirements.txt
      - name: Lint le code
        run: |
          flake8 app --count --max-line-length=127 --statistics
          flake8 tests --count --max-line-length=127 --statistics
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Requperer le code
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
      - name: install dependnces
        run: pip install -r requirements.txt
      - name: test with coverture
        run: PYTHONPATH=. pytest -v --cov=app
  build1:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Requperer le code
        uses: actions/checkout@v4
      - name: install dependnces
        run: pip install -r requirements.txt
      - name: python build1
        run: |
          pip install build
          python -m build
      - name: upload the result
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

    
